name: doctor_app
description: Offline-first Doctor App
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  drift: ^2.23.0
  drift_flutter: ^0.2.7
  file_picker: ^8.3.7
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.6.1
  google_mlkit_text_recognition: ^0.14.0
  google_sign_in: ^6.3.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: any
  local_auth: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.0.12
  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  speech_to_text: ^7.0.0
  auto_size_text: ^3.0.0
  sqlite3: ^2.9.4
  timezone: ^0.9.4
  sqlite3_flutter_libs: ^0.5.15
  syncfusion_flutter_pdf: ^31.2.16
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.21.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
