name: doctor_app
description: Offline-first Doctor App
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  drift: ^2.23.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.15
  sqlite3: ^2.1.0
  path_provider: ^2.0.12
  path: ^1.8.3
  intl: ^0.18.1
  flutter_local_notifications: ^18.0.0
  local_auth: ^2.1.6
  file_picker: ^8.0.0
  share_plus: ^10.0.0
  flutter_hooks: ^0.18.6
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.1
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  drift_dev: ^2.21.0

flutter:
  uses-material-design: true
  assets:
    - assets/
